version: '3'
services:
  backend:
    image: asia.gcr.io/outstagram-384310/outstagram-backend:0.0
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
